const {Schema, model} = require('mongoose')

const valuesSchema = new Schema( {
    publicado: String,
    porcentaje: Number,
    numero: {type: Number},
    // starting the name with an underscore is simply a convention
    // to denote this field as a reference
    // the type instructs Mongoose to set this up as a reference
    // to another document's _id property, which is automatically
    // generated by MongoDB. the ref field refers to the Model name
    //graph: { type: Schema.Types.ObjectId, ref: 'Graph' }
} );

module.exports = model('Values', valuesSchema)